'use client'

import { useState, useMemo, useEffect } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'
import { useAppStore } from '@/lib/store'
import { api } from '@/lib/utils/api-client'
import { safeParseJSON } from '@/lib/utils/safe-parse'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { ToolDialog } from '@/components/tools/tool-dialog'
import { AutoGeneratePreviewDialog } from '@/components/servers/auto-generate-preview-dialog'
import { AiPromptToolDialog } from '@/components/ai/ai-prompt-tool-dialog'
import {
  Card,
  CardContent,
} from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Switch } from '@/components/ui/switch'
import { Skeleton } from '@/components/ui/skeleton'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { cn } from '@/lib/utils'
import {
  Plus,
  Sparkles,
  Search,
  Wrench,
  Play,
  Copy,
  Trash2,
  Brain,
  Loader2,
  History,
  MoreHorizontal,
  Filter,
  LayoutGrid,
  List,
  ChevronDown,
  Zap,
  Database,
  FileCode,
  Puzzle,
  PackageOpen,
  Server,
  GitBranch,
} from 'lucide-react'

const CATEGORY_COLORS: Record<string, string> = {
  CRUD: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
  Find: 'bg-amber-500/20 text-amber-400 border-amber-500/30',
  Script: 'bg-violet-500/20 text-violet-400 border-violet-500/30',
  Custom: 'bg-slate-500/20 text-slate-300 border-slate-500/30',
}

const CATEGORY_ICONS: Record<string, typeof Database> = {
  CRUD: Database,
  Find: Search,
  Script: FileCode,
  Custom: Puzzle,
}

export function ToolsPage() {
  const router = useRouter()
  const currentServerId = useAppStore((s) => s.currentServerId)
  const currentBranchId = useAppStore((s) => s.currentBranchId)
  const setCurrentServer = useAppStore((s) => s.setCurrentServer)
  const setCurrentBranch = useAppStore((s) => s.setCurrentBranch)
  const setShowToolDialog = useAppStore((s) => s.setShowToolDialog)
  const setShowAiDialog = useAppStore((s) => s.setShowAiDialog)

  
  const queryClient = useQueryClient()

  // Filters
  const [searchQuery, setSearchQuery] = useState('')
  const [categoryFilter, setCategoryFilter] = useState<string>('all')
  const [statusFilter, setStatusFilter] = useState<string>('all')
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid')

  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false)
  const [showAiPromptDialog, setShowAiPromptDialog] = useState(false)

  const [aiPrefilledData, setAiPrefilledData] = useState<any>(null)

  // Fetch servers
  const { data: servers = [], isLoading: isLoadingServers } = useQuery<any[]>({
    queryKey: ['servers'],
    queryFn: () => api.get<any[]>('/api/servers')
  })

  // Selected server object helper
  const selectedServer = useMemo(() => {
    return servers.find(s => s.id === currentServerId)
  }, [servers, currentServerId])

  // Handle server selection change
  const handleServerChange = (serverId: string) => {
    setCurrentServer(serverId)
    const serverObj = servers.find(s => s.id === serverId)
    if (serverObj?.branches) {
      const defBranch = serverObj.branches.find((b: any) => b.isDefault)
      if (defBranch) {
        setCurrentBranch(defBranch.id)
      } else {
        setCurrentBranch(null)
      }
    } else {
      setCurrentBranch(null)
    }
  }

  // Auto-select default branch if none selected or if selected doesn't belong to current server
  useEffect(() => {
    if (selectedServer?.branches) {
      const isValidBranch = selectedServer.branches.some((b: any) => b.id === currentBranchId)
      if (!isValidBranch) {
        const defBranch = selectedServer.branches.find((b: any) => b.isDefault)
        if (defBranch) {
          setCurrentBranch(defBranch.id)
        }
      }
    }
  }, [selectedServer, currentBranchId, setCurrentBranch])

  // Fetch tools
  const { data: tools = [], isLoading, isError, error } = useQuery({
    queryKey: ['tools', currentServerId, currentBranchId],
    queryFn: async () => {
      if (!currentServerId) return []
      const url = currentBranchId
        ? `/api/branches/${currentBranchId}/tools`
        : `/api/servers/${currentServerId}/tools`
      return api.get<any[]>(url)
    },
    enabled: !!currentServerId,
  })

  // Toggle enabled mutation
  const toggleMutation = useMutation({
    mutationFn: async ({ id, isEnabled }: { id: string; isEnabled: boolean }) => {
      const url = currentBranchId
        ? `/api/branches/${currentBranchId}/tools/${id}`
        : `/api/servers/${currentServerId}/tools/${id}`
      const body = currentBranchId
        ? { enabled: !isEnabled }
        : { isEnabled: !isEnabled }
      return api.put(url, body)
    },
    onMutate: async ({ id, isEnabled }) => {
      const queryKey = ['tools', currentServerId, currentBranchId]
      await queryClient.cancelQueries({ queryKey })
      const previous = queryClient.getQueryData(queryKey)
      queryClient.setQueryData(queryKey, (old: any[]) =>
        old?.map(t => t.id === id ? { ...t, isEnabled: !isEnabled } : t) ?? old
      )
      return { previous, queryKey }
    },
    onError: (_err, _vars, ctx: any) => {
      if (ctx?.previous !== undefined) queryClient.setQueryData(ctx.queryKey, ctx.previous)
      toast.error('Failed to toggle tool')
    },
    onSettled: () => {
      queryClient.invalidateQueries({ queryKey: ['tools', currentServerId, currentBranchId] })
    },
  })

  // Duplicate mutation
  const duplicateMutation = useMutation({
    mutationFn: async (tool: Record<string, unknown>) => {
      const url = currentBranchId
        ? `/api/branches/${currentBranchId}/tools`
        : `/api/servers/${currentServerId}/tools`
      const body = {
        name: `${(tool.name as string)} (Copy)`,
        description: (tool.description as string) || '',
        category: (tool.category as string) || 'custom',
        handlerType: (tool.fmMethod as string) || 'find',
        inputSchema: typeof tool.inputSchema === 'string' ? safeParseJSON(tool.inputSchema, {}) : tool.inputSchema,
        handlerConfig: typeof tool.handlerConfig === 'string' ? safeParseJSON(tool.handlerConfig, {}) : tool.handlerConfig,
        enabled: tool.isEnabled ?? true,
      }
      return api.post(url, body)
    },
    onSuccess: () => {
      toast.success('Tool duplicated')
      queryClient.invalidateQueries({ queryKey: ['tools', currentServerId, currentBranchId] })
    },
    onError: () => {
      toast.error('Failed to duplicate tool')
    },
  })

  // Delete mutation
  const deleteMutation = useMutation({
    mutationFn: async (id: string) => {
      const url = currentBranchId
        ? `/api/branches/${currentBranchId}/tools/${id}`
        : `/api/servers/${currentServerId}/tools/${id}`
      return api.delete(url)
    },
    onSuccess: () => {
      toast.success('Tool deleted')
      queryClient.invalidateQueries({ queryKey: ['tools', currentServerId, currentBranchId] })
    },
    onError: () => {
      toast.error('Failed to delete tool')
    },
  })

  // Filter tools
  const filteredTools = useMemo(() => {
    return (tools as any[]).filter((tool: any) => {
      const name = (tool.name as string).toLowerCase()
      const desc = (tool.description as string).toLowerCase()
      const category = tool.category as string
      const enabled = tool.isEnabled as boolean

      const matchesSearch =
        !searchQuery || name.includes(searchQuery.toLowerCase()) || desc.includes(searchQuery.toLowerCase())

      const matchesCategory = categoryFilter === 'all' || category === categoryFilter
      const matchesStatus =
        statusFilter === 'all' ||
        (statusFilter === 'enabled' && enabled) ||
        (statusFilter === 'disabled' && !enabled)

      return matchesSearch && matchesCategory && matchesStatus
    })
  }, [tools, searchQuery, categoryFilter, statusFilter])

  const enabledCount = (tools as any[]).filter((t: any) => t.isEnabled).length
  const totalCount = tools.length

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex flex-col xl:flex-row items-start xl:items-center justify-between gap-4 mb-6 border-b pb-5">
        <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4">
          <div className="flex items-center gap-2.5">
            <div className="size-10 rounded-xl bg-indigo-500/10 text-indigo-400 flex items-center justify-center border border-indigo-500/20">
              <Wrench className="size-5" />
            </div>
            <div>
              <h1 className="text-2xl font-bold tracking-tight">Tools</h1>
              <p className="text-xs text-muted-foreground mt-0.5">
                {currentServerId ? `${totalCount} tools defined · ${enabledCount} enabled` : 'Select a server to view and manage tools'}
              </p>
            </div>
          </div>

          {/* Server & Branch Selectors */}
          <div className="flex flex-wrap items-center gap-2 mt-2 sm:mt-0">
            <div className="flex items-center gap-1.5 bg-muted/40 border rounded-lg px-2.5 py-1">
              <Server className="size-3.5 text-muted-foreground" />
              <span className="text-[11px] font-medium text-muted-foreground mr-0.5">Server:</span>
              <Select value={currentServerId || 'none'} onValueChange={handleServerChange}>
                <SelectTrigger className="h-7 border-none bg-transparent hover:bg-muted/80 shadow-none px-2 focus:ring-0 w-[160px] text-xs font-semibold">
                  <SelectValue placeholder="Select Server" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="none" disabled>Select a Server</SelectItem>
                  {servers.map((s) => (
                    <SelectItem key={s.id} value={s.id}>
                      {s.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {selectedServer && (
              <div className="flex items-center gap-1.5 bg-muted/40 border rounded-lg px-2.5 py-1 animate-in fade-in slide-in-from-left-2 duration-200">
                <GitBranch className="size-3.5 text-muted-foreground" />
                <span className="text-[11px] font-medium text-muted-foreground mr-0.5">Branch:</span>
                <Select 
                  value={currentBranchId || 'none'} 
                  onValueChange={(val) => setCurrentBranch(val === 'none' ? null : val)}
                >
                  <SelectTrigger className="h-7 border-none bg-transparent hover:bg-muted/80 shadow-none px-2 focus:ring-0 w-[140px] text-xs font-semibold">
                    <SelectValue placeholder="Select Branch" />
                  </SelectTrigger>
                  <SelectContent>
                    {selectedServer.branches?.map((b: any) => (
                      <SelectItem key={b.id} value={b.id}>
                        {b.name} {b.isDefault && '(default)'}
                      </SelectItem>
                    )) || <SelectItem value="none" disabled>No branches</SelectItem>}
                  </SelectContent>
                </Select>
              </div>
            )}
          </div>
        </div>

        <div className="flex items-center gap-2 w-full xl:w-auto xl:justify-end">
          <Button
            variant="outline"
            size="sm"
            onClick={() => setShowAiPromptDialog(true)}
            className="gap-1.5 flex-1 xl:flex-initial"
            disabled={!currentServerId}
          >
            <Sparkles className="size-3.5" />
            <span>AI Assistant</span>
          </Button>

          <Button
            size="sm"
            onClick={() => setShowToolDialog(true)}
            className="gap-1.5 flex-1 xl:flex-initial"
            disabled={!currentServerId}
          >
            <Plus className="size-3.5" />
            <span>New Tool</span>
          </Button>

          <Button
            id="auto-generate-btn"
            variant="secondary"
            size="sm"
            onClick={() => setShowAutoGenerateDialog(true)}
            disabled={!currentServerId}
            className="gap-1.5 bg-indigo-500/10 text-indigo-400 hover:bg-indigo-500/20 border border-indigo-500/10 flex-1 xl:flex-initial"
          >
            <Brain className="size-3.5" />
            <span>Auto-Generate</span>
          </Button>
        </div>
      </div>

      {/* Main Content Area */}
      {!currentServerId ? (
        <div className="flex-1 flex flex-col items-center justify-center border border-dashed rounded-xl p-8 bg-muted/5 min-h-[350px]">
          <div className="max-w-md text-center space-y-4">
            <div className="mx-auto size-16 rounded-2xl bg-indigo-500/10 text-indigo-400 flex items-center justify-center border border-indigo-500/20 shadow-inner animate-pulse">
              <Server className="size-8" />
            </div>
            <div className="space-y-2">
              <h2 className="text-xl font-bold tracking-tight">No Server Selected</h2>
              <p className="text-sm text-muted-foreground">
                To view, test, and manage tools, select an active MCP server first.
              </p>
            </div>
            <div className="flex flex-col gap-3 items-center justify-center pt-2">
              <Select value="none" onValueChange={handleServerChange}>
                <SelectTrigger className="w-[260px] h-10 font-medium border-primary/20 hover:border-primary/40 focus:ring-1 focus:ring-indigo-500">
                  <SelectValue placeholder="Select an MCP Server" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="none" disabled>Choose a server...</SelectItem>
                  {servers.map((s) => (
                    <SelectItem key={s.id} value={s.id}>
                      {s.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <p className="text-xs text-muted-foreground">
                Don't have a server yet? Go to the <Link href="/servers" className="text-indigo-400 hover:underline font-semibold transition-colors">Servers page</Link> to create one.
              </p>
            </div>
          </div>
        </div>
      ) : (
        <>
          {/* Filter Bar */}
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-2 mb-4">
            <div className="relative flex-1 w-full sm:max-w-sm">
              <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 size-3.5 text-muted-foreground" />
          <Input
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search tools by name or description..."
            className="h-8 pl-8 text-sm"
          />
        </div>
        <div className="flex items-center gap-2">
          <Select value={categoryFilter} onValueChange={setCategoryFilter}>
            <SelectTrigger className="h-8 w-[130px] text-xs">
              <Filter className="size-3 mr-1" />
              <SelectValue placeholder="Category" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Categories</SelectItem>
              <SelectItem value="CRUD">CRUD</SelectItem>
              <SelectItem value="Find">Find</SelectItem>
              <SelectItem value="Script">Script</SelectItem>
              <SelectItem value="Custom">Custom</SelectItem>
            </SelectContent>
          </Select>
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="h-8 w-[110px] text-xs">
              <SelectValue placeholder="Status" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Status</SelectItem>
              <SelectItem value="enabled">Enabled</SelectItem>
              <SelectItem value="disabled">Disabled</SelectItem>
            </SelectContent>
          </Select>
          <div className="flex border rounded-md">
            <Button
              variant={viewMode === 'grid' ? 'secondary' : 'ghost'}
              size="sm"
              onClick={() => setViewMode('grid')}
              className="h-8 w-8 p-0 rounded-r-none"
              aria-label="Grid view"
            >
              <LayoutGrid className="size-3.5" />
            </Button>
            <Button
              variant={viewMode === 'list' ? 'secondary' : 'ghost'}
              size="sm"
              onClick={() => setViewMode('list')}
              className="h-8 w-8 p-0 rounded-l-none"
              aria-label="List view"
            >
              <List className="size-3.5" />
            </Button>
          </div>
        </div>
      </div>

      {/* Tools Content */}
      {isError ? (
        <Card className="border-destructive/30 bg-destructive/5">
          <CardContent className="p-6 text-center">
            <p className="text-sm text-destructive font-medium">Failed to load tools</p>
            <p className="text-xs text-muted-foreground mt-1">
              {(error as any)?.message || 'An unexpected error occurred'}
            </p>
            <Button
              variant="outline"
              size="sm"
              className="mt-3"
              onClick={() => queryClient.invalidateQueries({ queryKey: ['tools', currentServerId, currentBranchId] })}
            >
              Retry
            </Button>
          </CardContent>
        </Card>
      ) : isLoading ? (
        <div className={cn('grid gap-3 flex-1', viewMode === 'grid' ? 'grid-cols-1 md:grid-cols-2 xl:grid-cols-3' : 'grid-cols-1')}>
          {Array.from({ length: 6 }).map((_, i) => (
            <Skeleton key={i} className="h-40 rounded-lg" />
          ))}
        </div>
      ) : filteredTools.length === 0 ? (
        <EmptyState
          hasTools={tools.length > 0}
          onCreateNew={() => setShowToolDialog(true)}
          onAiSuggest={() => setShowAiPromptDialog(true)}
        />
      ) : viewMode === 'grid' ? (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3 flex-1 overflow-y-auto pr-1 custom-scrollbar">
          {(filteredTools as any[]).map((tool: any) => (
            <ToolCard
              key={tool.id as string}
              tool={tool}
              onEdit={() => setShowToolDialog(true, tool.id as string)}
              onTest={() => router.push('/playground')}
              onDuplicate={() => duplicateMutation.mutate(tool)}
              onDelete={() => deleteMutation.mutate(tool.id as string)}
              onToggle={() =>
                toggleMutation.mutate({
                  id: tool.id as string,
                  isEnabled: tool.isEnabled as boolean,
                })
              }
            />
          ))}
        </div>
      ) : (
        <div className="flex flex-col gap-2 flex-1 overflow-y-auto pr-1 custom-scrollbar">
          {(filteredTools as any[]).map((tool: any) => (
            <ToolListItem
              key={tool.id as string}
              tool={tool}
              onEdit={() => setShowToolDialog(true, tool.id as string)}
              onTest={() => router.push('/playground')}
              onDuplicate={() => duplicateMutation.mutate(tool)}
              onDelete={() => deleteMutation.mutate(tool.id as string)}
              onToggle={() =>
                toggleMutation.mutate({
                  id: tool.id as string,
                  isEnabled: tool.isEnabled as boolean,
                })
              }
            />
          ))}
        </div>
      )}
      </>
      )}

      <ToolDialog prefilledData={aiPrefilledData} />
      {showAutoGenerateDialog && (
        <AutoGeneratePreviewDialog
          open={showAutoGenerateDialog}
          onOpenChange={setShowAutoGenerateDialog}
          serverId={currentServerId || ''}
        />
      )}
      {showAiPromptDialog && (
        <AiPromptToolDialog
          open={showAiPromptDialog}
          onOpenChange={setShowAiPromptDialog}
          serverId={currentServerId || ''}
        />
      )}
    </div>
  )
}

// ===== Tool Card (Grid View) =====
function ToolCard({
  tool,
  onEdit,
  onTest,
  onDuplicate,
  onDelete,
  onToggle,
}: {
  tool: Record<string, unknown>
  onEdit: () => void
  onTest: () => void
  onDuplicate: () => void
  onDelete: () => void
  onToggle: () => void
}) {
  const category = (tool.category as string) || 'Custom'
  const CategoryIcon = CATEGORY_ICONS[category] || Puzzle
  const categoryColor = CATEGORY_COLORS[category] || CATEGORY_COLORS.Custom

  return (
    <AlertDialog>
      <Card
        className={cn(
          'group hover:border-primary/40 transition-all duration-200',
          !(tool.isEnabled as boolean) && 'opacity-60'
        )}
      >
        <CardContent className="p-4 space-y-3">
          {/* Header */}
          <div className="flex items-start justify-between gap-2">
            <div className="flex items-start gap-2 min-w-0">
              <div className={cn('flex-shrink-0 size-8 rounded-lg flex items-center justify-center mt-0.5', categoryColor)}>
                <CategoryIcon className="size-4" />
              </div>
              <div className="min-w-0">
                <h3 className="text-sm font-semibold truncate flex items-center gap-1.5">
                  {tool.name as string}
                  {(tool.isAiGenerated as boolean) && (
                    <Zap className="size-3 text-violet-400 flex-shrink-0" />
                  )}
                </h3>
                <p className="text-xs text-muted-foreground line-clamp-2 mt-0.5">
                  {tool.description as string}
                </p>
              </div>
            </div>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-7 w-7 p-0 opacity-0 group-hover:opacity-100 transition-opacity flex-shrink-0"
                  aria-label="More options"
                >
                  <MoreHorizontal className="size-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-48">
                <DropdownMenuItem onClick={onEdit} className="gap-2">
                  <Wrench className="size-3.5" />
                  Edit
                </DropdownMenuItem>
                <DropdownMenuItem onClick={onTest} className="gap-2">
                  <Play className="size-3.5" />
                  Test in Playground
                </DropdownMenuItem>
                <DropdownMenuItem onClick={onDuplicate} className="gap-2">
                  <Copy className="size-3.5" />
                  Duplicate
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <AlertDialogTrigger asChild>
                  <DropdownMenuItem onSelect={(e) => e.preventDefault()} className="gap-2 text-destructive focus:text-destructive">
                    <Trash2 className="size-3.5" />
                    Delete
                  </DropdownMenuItem>
                </AlertDialogTrigger>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>

          {/* Tags */}
          <div className="flex flex-wrap items-center gap-1.5">
            <Badge variant="outline" className={cn('text-[10px]', categoryColor)}>
              {category}
            </Badge>
            {(tool.fmLayout as string) && (
              <Badge variant="secondary" className="text-[10px] gap-0.5">
                <Database className="size-2.5" />
                {tool.fmLayout as string}
              </Badge>
            )}
            {(tool.fmScript as string) && (
              <Badge variant="secondary" className="text-[10px] gap-0.5">
                <FileCode className="size-2.5" />
                {tool.fmScript as string}
              </Badge>
            )}
          </div>

          {/* Footer */}
          <div className="flex items-center justify-between pt-1">
            <div className="flex items-center gap-2 text-xs text-muted-foreground">
              <Badge variant="outline" className="text-[10px] font-mono">
                v{tool.version as number}
              </Badge>
            </div>
            <Switch
              checked={tool.isEnabled as boolean}
              onCheckedChange={onToggle}
              className="scale-75"
            />
          </div>
        </CardContent>
      </Card>

      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>Delete Tool</AlertDialogTitle>
          <AlertDialogDescription>
            Delete &quot;{tool.name as string}&quot;? It will be removed from this server. Execution history is preserved.
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel autoFocus>Cancel</AlertDialogCancel>
          <AlertDialogAction onClick={onDelete} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">
            Delete
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  )
}

// ===== Tool List Item =====
function ToolListItem({
  tool,
  onEdit,
  onTest,
  onDuplicate,
  onDelete,
  onToggle,
}: {
  tool: Record<string, unknown>
  onEdit: () => void
  onTest: () => void
  onDuplicate: () => void
  onDelete: () => void
  onToggle: () => void
}) {
  const category = (tool.category as string) || 'Custom'
  const categoryColor = CATEGORY_COLORS[category] || CATEGORY_COLORS.Custom

  return (
    <AlertDialog>
      <Card className={cn('hover:border-primary/40 transition-colors', !(tool.isEnabled as boolean) && 'opacity-60')}>
        <CardContent className="p-3">
          <div className="flex items-center gap-3">
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2">
                <h3 className="text-sm font-semibold truncate">
                  {tool.name as string}
                  {(tool.isAiGenerated as boolean) && (
                    <Zap className="size-3 text-violet-400 inline ml-1" />
                  )}
                </h3>
                <Badge variant="outline" className={cn('text-[10px]', categoryColor)}>
                  {category}
                </Badge>
              </div>
              <p className="text-xs text-muted-foreground truncate mt-0.5">
                {tool.description as string}
              </p>
            </div>
            <div className="flex items-center gap-2 flex-shrink-0">
              {(tool.fmLayout as string) && (
                <Badge variant="secondary" className="text-[10px] gap-0.5 hidden sm:inline-flex">
                  <Database className="size-2.5" />
                  {tool.fmLayout as string}
                </Badge>
              )}
              <Badge variant="outline" className="text-[10px] font-mono">
                v{tool.version as number}
              </Badge>
              <Switch checked={tool.isEnabled as boolean} onCheckedChange={onToggle} className="scale-75" />
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="ghost" size="sm" className="h-7 w-7 p-0" aria-label="More options">
                    <MoreHorizontal className="size-4" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="w-48">
                  <DropdownMenuItem onClick={onEdit} className="gap-2">
                    <Wrench className="size-3.5" />
                    Edit
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={onTest} className="gap-2">
                    <Play className="size-3.5" />
                    Test in Playground
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={onDuplicate} className="gap-2">
                    <Copy className="size-3.5" />
                    Duplicate
                  </DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <AlertDialogTrigger asChild>
                    <DropdownMenuItem onSelect={(e) => e.preventDefault()} className="gap-2 text-destructive focus:text-destructive">
                      <Trash2 className="size-3.5" />
                      Delete
                    </DropdownMenuItem>
                  </AlertDialogTrigger>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
        </CardContent>
      </Card>

      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>Delete Tool</AlertDialogTitle>
          <AlertDialogDescription>
            Delete &quot;{tool.name as string}&quot;? It will be removed from this server. Execution history is preserved.
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel autoFocus>Cancel</AlertDialogCancel>
          <AlertDialogAction onClick={onDelete} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">
            Delete
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  )
}

// ===== Empty State =====
function EmptyState({
  hasTools,
  onCreateNew,
  onAiSuggest,
}: {
  hasTools: boolean
  onCreateNew: () => void
  onAiSuggest: () => void
}) {
  return (
    <div className="flex-1 flex items-center justify-center">
      <div className="text-center max-w-md space-y-4">
        <div className="mx-auto size-16 rounded-2xl bg-muted/30 flex items-center justify-center">
          <PackageOpen className="size-8 text-muted-foreground" />
        </div>
        <div>
          <h2 className="text-lg font-semibold">
            {hasTools ? 'No tools match your filters' : 'No tools defined yet'}
          </h2>
          <p className="text-sm text-muted-foreground mt-1">
            {hasTools
              ? 'Try adjusting your search or filter criteria to find what you are looking for.'
              : 'Create your first tool manually, use AI to suggest one, or auto-generate a full suite of tools based on the schema.'}
          </p>
        </div>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-2">
          {!hasTools && (
            <>
              <Button variant="outline" onClick={onAiSuggest} className="gap-1.5">
                <Sparkles className="size-3.5" />
                Single Tool
              </Button>
              <Button variant="secondary" onClick={() => {
                const btn = document.getElementById('auto-generate-btn');
                if (btn) btn.click();
              }} className="gap-1.5 bg-indigo-500/10 text-indigo-500 hover:bg-indigo-500/20">
                <Brain className="size-3.5" />
                Auto-Generate Suite
              </Button>
            </>
          )}
          <Button onClick={onCreateNew} className="gap-1.5">
            <Plus className="size-3.5" />
            New Tool
          </Button>
        </div>
      </div>
    </div>
  )
}
